/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RandomCatRouteImport } from './routes/random-cat'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as JokesRouteImport } from './routes/jokes'
import { Route as MealIdRouteImport } from './routes/meal/$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomCatRoute = RandomCatRouteImport.update({
  id: '/random-cat',
  path: '/random-cat',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesRoute = JokesRouteImport.update({
  id: '/jokes',
  path: '/jokes',
  getParentRoute: () => rootRouteImport,
} as any)
const MealIdRoute = MealIdRouteImport.update({
  id: '/meal/$id',
  path: '/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/jokes': typeof JokesRoute
  '/meals': typeof MealsRoute
  '/products': typeof ProductsRoute
  '/quotes': typeof QuotesRoute
  '/random-cat': typeof RandomCatRoute
  '/users': typeof UsersRoute
  '/videos': typeof VideosRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRoutesByTo {
  '/jokes': typeof JokesRoute
  '/meals': typeof MealsRoute
  '/products': typeof ProductsRoute
  '/quotes': typeof QuotesRoute
  '/random-cat': typeof RandomCatRoute
  '/users': typeof UsersRoute
  '/videos': typeof VideosRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/jokes': typeof JokesRoute
  '/meals': typeof MealsRoute
  '/products': typeof ProductsRoute
  '/quotes': typeof QuotesRoute
  '/random-cat': typeof RandomCatRoute
  '/users': typeof UsersRoute
  '/videos': typeof VideosRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/jokes'
    | '/meals'
    | '/products'
    | '/quotes'
    | '/random-cat'
    | '/users'
    | '/videos'
    | '/meal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/jokes'
    | '/meals'
    | '/products'
    | '/quotes'
    | '/random-cat'
    | '/users'
    | '/videos'
    | '/meal/$id'
  id:
    | '__root__'
    | '/jokes'
    | '/meals'
    | '/products'
    | '/quotes'
    | '/random-cat'
    | '/users'
    | '/videos'
    | '/meal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  JokesRoute: typeof JokesRoute
  MealsRoute: typeof MealsRoute
  ProductsRoute: typeof ProductsRoute
  QuotesRoute: typeof QuotesRoute
  RandomCatRoute: typeof RandomCatRoute
  UsersRoute: typeof UsersRoute
  VideosRoute: typeof VideosRoute
  MealIdRoute: typeof MealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-cat': {
      id: '/random-cat'
      path: '/random-cat'
      fullPath: '/random-cat'
      preLoaderRoute: typeof RandomCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes': {
      id: '/jokes'
      path: '/jokes'
      fullPath: '/jokes'
      preLoaderRoute: typeof JokesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$id': {
      id: '/meal/$id'
      path: '/meal/$id'
      fullPath: '/meal/$id'
      preLoaderRoute: typeof MealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  JokesRoute: JokesRoute,
  MealsRoute: MealsRoute,
  ProductsRoute: ProductsRoute,
  QuotesRoute: QuotesRoute,
  RandomCatRoute: RandomCatRoute,
  UsersRoute: UsersRoute,
  VideosRoute: VideosRoute,
  MealIdRoute: MealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
